# Generated by Django 4.2.7 on 2023-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toast',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
